#include"header.cpp"
void main()
{
int key=0,i;
clrscr();
gotoxy(10,10);
i=1;
textcolor(i);
cprintf("%c",179);
gotoxy(11,10);
i=2;
textcolor(i);
cprintf("%c",179);
gotoxy(12,10);
i=3;
textcolor(i);
cprintf("%c",179);
gotoxy(13,10);
i=4;
textcolor(i);
cprintf("%c",179);
gotoxy(14,10);
i=5;
textcolor(i);
cprintf("%c",179);
gotoxy(15,10);
i=6;
textcolor(i);
cprintf("%c",179);
gotoxy(16,10);
i=7;
textcolor(i);
cprintf("%c",179);
gotoxy(17,10);
i=8;
textcolor(i);
cprintf("%c",179);
gotoxy(18,10);
i=9;
textcolor(i);
cprintf("%c",179);
gotoxy(19,10);
i=10;
textcolor(i);
cprintf("%c",179);
gotoxy(20,10);
i=11;
textcolor(i);
cprintf("%c",179);
gotoxy(21,10);
i=12;
textcolor(i);
cprintf("%c",179);
gotoxy(22,10);
i=13;
textcolor(i);
cprintf("%c",179);
gotoxy(23,10);
i=14;
textcolor(i);
cprintf("%c",179);
gotoxy(24,10);
i=15;
textcolor(i);
cprintf("%c",179);
gotoxy(25,10);
i=1;
textcolor(i);
cprintf("%c",179);
gotoxy(26,10);
i=2;
textcolor(i);
cprintf("%c",179);
gotoxy(27,10);
i=3;
textcolor(i);
cprintf("%c",179);
gotoxy(28,10);
i=4;
textcolor(i);
cprintf("%c",179);
gotoxy(29,10);
i=5;
textcolor(i);
cprintf("%c",179);
gotoxy(30,10);
i=6;
textcolor(i);
cprintf("%c",179);
gotoxy(31,10);
i=7;
textcolor(i);
cprintf("%c",179);
gotoxy(32,10);
i=8;
textcolor(i);
cprintf("%c",179);
gotoxy(33,10);
i=9;
textcolor(i);
cprintf("%c",179);
gotoxy(34,10);
i=10;
textcolor(i);
cprintf("%c",179);
gotoxy(35,10);
i=11;
textcolor(i);
cprintf("%c",179);
gotoxy(36,10);
i=12;
textcolor(i);
cprintf("%c",179);
gotoxy(37,10);
i=13;
textcolor(i);
cprintf("%c",179);
gotoxy(38,10);
i=14;
textcolor(i);
cprintf("%c",179);
gotoxy(39,10);
i=15;
textcolor(i);
cprintf("%c",179);
gotoxy(40,10);
i=1;
textcolor(i);
cprintf("%c",179);
gotoxy(41,10);
i=2;
textcolor(i);
cprintf("%c",179);
gotoxy(42,10);
i=3;
textcolor(i);
cprintf("%c",179);
gotoxy(43,10);
i=4;
textcolor(i);
cprintf("%c",179);
gotoxy(44,10);
i=5;
textcolor(i);
cprintf("%c",179);
gotoxy(45,10);
i=6;
textcolor(i);
cprintf("%c",179);
gotoxy(46,10);
i=7;
textcolor(i);
cprintf("%c",179);
gotoxy(47,10);
i=8;
textcolor(i);
cprintf("%c",179);
gotoxy(48,10);
i=9;
textcolor(i);
cprintf("%c",179);
gotoxy(49,10);
i=10;
textcolor(i);
cprintf("%c",179);
gotoxy(50,10);
i=11;
textcolor(i);
cprintf("%c",179);
gotoxy(51,10);
i=12;
textcolor(i);
cprintf("%c",179);
gotoxy(52,10);
i=13;
textcolor(i);
cprintf("%c",179);
gotoxy(53,10);
i=14;
textcolor(i);
cprintf("%c",179);
gotoxy(54,10);
i=15;
textcolor(i);
cprintf("%c",179);
gotoxy(55,10);
i=1;
textcolor(i);
cprintf("%c",179);
gotoxy(56,10);
i=2;
textcolor(i);
cprintf("%c",179);
gotoxy(57,10);
i=3;
textcolor(i);
cprintf("%c",179);
gotoxy(58,10);
i=4;
textcolor(i);
cprintf("%c",179);
gotoxy(59,10);
i=5;
textcolor(i);
cprintf("%c",179);
gotoxy(60,10);
i=6;
textcolor(i);
cprintf("%c",179);
gotoxy(61,10);
i=7;
textcolor(i);
cprintf("%c",179);
do
{
key=getch();
switch(key)
{
	case 65:
	sound(1480);
	gotoxy(46,10);
	textcolor(BLACK);
	cprintf("%c",179);
	delay(50);
	textcolor(GREEN);
	break;

	case 66:
	sound(4684);
	gotoxy(59,10);
	break;

	case 67:
	sound(4060);
	gotoxy(57,10);
	break;

	case 68:

	sound(1820);
	gotoxy(48,10);
	break;

	case 69:
	sound(600);
	gotoxy(38,10);
	break;

	case 70:
	sound(1990);
	gotoxy(49,10);
	break;

	case 71:
	sound(2160);
	gotoxy(50,10);
	break;

	case 72:
	sound(2330);
	gotoxy(51,10);
	break;

	case 73:
	sound(970);
	gotoxy(43,10);
	break;

	case 74:
	sound(2500);
	gotoxy(52,10);
	break;

	case 75:
	sound(2812);
	gotoxy(53,10);
	break;

	case 76:
	sound(3124);
	gotoxy(54,10);
	break;

	case 77:
	sound(5308);
	gotoxy(61,10);
	break;

	case 78:
	sound(4996);
	gotoxy(60,10);
	break;

	case 79:
	sound(1140);
	gotoxy(44,10);
	break;

	case 80:
	sound(1310);
	gotoxy(45,10);
	break;

	case 81:
	sound(500);
	gotoxy(36,10);
	break;

	case 82:
	sound(650);
	gotoxy(39,10);
	break;

	case 83:
	sound(1650);
	gotoxy(47,10);
	break;

	case 84:
	sound(700);
	gotoxy(40,10);
	break;

	case 85:
	sound(800);
	gotoxy(42,10);
	break;

	case 86:
	sound(4372);
	gotoxy(58,10);
	break;

	case 87:
	sound(550);
	gotoxy(37,10);
	break;

	case 88:
	sound(3748);
	gotoxy(56,10);
	break;

	case 89:
	sound(750);
	gotoxy(41,10);
	break;

	case 90:
	sound(3436);
	gotoxy(55,10);
	break;

	case 97:
	sound(90);
	gotoxy(20,10);
	break;

	case 98:
	sound(350);
	gotoxy(33,10);
	break;

	case 99:
	sound(264);
	gotoxy(31,10);
	break;

	case 100:
	sound(110);
	gotoxy(22,10);
	break;

	case 101:
	sound(31);
	gotoxy(12,10);
	break;

	case 102:
	sound(120);
	gotoxy(23,10);
	break;

	case 103:
	sound(130);
	gotoxy(24,10);
	break;

	case 104:
	sound(140);
	gotoxy(25,10);
	break;

	case 105:
	sound(60);
	gotoxy(17,10);
	break;

	case 106:
	sound(150);
	gotoxy(26,10);
	break;

	case 107:
	sound(160);
	gotoxy(27,10);
	break;


	case 108:
	sound(186);
	gotoxy(28,10);
	break;

	case 109:
	sound(450);
	gotoxy(35,10);
	break;

	case 110:
	sound(400);
	gotoxy(34,10);
	break;

	case 111:
	sound(70);
	gotoxy(18,10);
	break;

	case 112:
	sound(80);
	gotoxy(19,10);
	break;

	case 113:
	sound(25);
	gotoxy(10,10);
	break;

	case 114:
	sound(34);
	gotoxy(13,10);
	break;

	case 115:
	sound(100);
	gotoxy(21,10);
	break;

	case 116:
	sound(37);
	gotoxy(14,10);
	break;

	case 117:
	sound(50);
	gotoxy(16,10);
	break;

	case 118:
	sound(290);
	gotoxy(32,10);
	break;

	case 119:
	sound(28);
	gotoxy(11,10);
	break;

	case 120:
	sound(238);
	gotoxy(30,10);
	break;

	case 121:
	sound(40);
	gotoxy(15,10);

	break;

	case 122:
	sound(212);
	gotoxy(29,10);
	break;

      /*	case 13:
	cout<<"\n";
	break;  */

	case 32:
	nosound();   //to switch off the speaker.
	break;
	/*
	case 48:
	sound();
	gotoxy();
	break;

	case 49:
	sound();
	gotoxy();
	break;

	case 50:
	sound();
	gotoxy();
	break;

	case 51:
	sound();
	gotoxy();
	break;

	case 52:
	sound();
	gotoxy();
	break;

	case 53:
	sound();
	gotoxy();
	break;

	case 54:
	sound();
	gotoxy();
	break;

	case 55:
	sound();
	gotoxy();
	break;

	case 56:
	sound();
	gotoxy();
	break;

	case 8:
	cout<<"\b"<<" ";
	break;

	case 63:
	sound();
	gotoxy();
	break;

	case 46:
	sound();
	gotoxy();
	break;

	case 44:
	sound();
	gotoxy();
	break; */

 default:
	return;
}
}
while(1);
}